---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/favorite_houses":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list favorite_houses
      responses:
        '200':
          description: successful
    post:
      summary: create favorite_house
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/favorite_houses/{id}":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete favorite_house
      responses:
        '200':
          description: successful
  "/api/v1/houses":
    get:
      summary: list houses
      responses:
        '200':
          description: successful
    post:
      summary: create house
      responses:
        '200':
          description: successful
  "/api/v1/houses/new":
    get:
      summary: new house
      responses:
        '200':
          description: successful
  "/api/v1/houses/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit house
      responses:
        '200':
          description: successful
  "/api/v1/houses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show house
      responses:
        '200':
          description: successful
    patch:
      summary: update house
      responses:
        '200':
          description: successful
    put:
      summary: update house
      responses:
        '200':
          description: successful
    delete:
      summary: delete house
      responses:
        '200':
          description: successful
  "/api/users":
    post:
      summary: Creates a user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
servers:
- url: https://localhost
  variables:
    defaultHost:
      default: www.example.com
